spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_postgres
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
